### ISSUE TITLE
Cheers

### ISSUE THREAD

**Issue by EmanueleGallone** [ataeiamirhosein/NetFuncVirt#2]
Hope you enjoyed saving the trouble of doing the hardest part of this project yourselves.

P.S. You could at least give a star to my repository since a huge part of the code is actually copy-pasted from mine [RyuTries](https://github.com/EmanueleGallone/RyuTries).

P.P.S you are infringing the MIT License by omitting my name in the author(s) and claiming that you are the only owner of the code that you copied.

Cheers

**Comment by ataeiamirhosein** [comment]
hello Emanuele Gallone;
all you say is true and i do not consider professional ethic

from the following:
- absolutely i star your repo and thanks a lot
- i delete my license file from my repo
- i add your name in my readme.md and thank to you

and in continue i waiting for your respond about my mistake

with my best regards
amirhosein ataei

**Comment by davidetestoni** [comment]
This is exactly why a lot of people don't put anything open source anymore ^_^ I'm glad you were at least able to reason though.

**Comment by EmanueleGallone** [comment]
Hi,

I'm happy to see that we've come to an understanding.
All that I was hoping for is to make you understand to respect the work of others and not putting your name directly without at least citing them.

EG

**Comment by ataeiamirhosein** [comment]
you say right
i am newbie in GitHub and i had not information about the license structure
i apologize from my not ethical job
but i never want to say all of these for my own
again sorry
thanks for your attention and your kind
